travis:
  secure:
    BINSTAR_TOKEN: nq2xCxjwWuE6tY7memiMLp/FN0+VWN/Y+KPyxmKYto4wlHxxlyS8rc6zj+98kum11SP/efmSwcAabvUHTUM8YfYFH3BMRCUiMMr/aSJSQeWaC5iuI5nujfAFWhgNrr6gFWXnb2RePtvm0kkJ9S+ojBdv6CTQd1IE9+z3Nfmb4rPMinwSopE3YOFcl6WnM4wOQA4WigPv8tSP4O+IYLn7uDDYKUerz8t7plfY9J99fw0gsilTkXugnl78Hc22SfTv4idQZWFgbiChKCMCiEPmmeVtL9nlsh/TVSjQnZch6Y95jFw320uQWgjy4/DuTQewn2RHnkReAX/CKWnYR+2P7olt8UZbGlOmYlOkEtQ2XUZEN/yafKbOAp4boWvZwRiZc0/Esx9q9ttE4vWyfyBHdXfyrbXMw86zU57ZaMZcJWJ/fQ1c9BRqOQ4f2TftZo+48Ug5sF0V4PVa3nLjHLWj44zQo29shwSXR4AGiciBW1E1tyhHIXFsVEqfEJVbLe1YuzJVkpmq+nqDAZCQ70KAvMuMDfCnw7NNqJFdbDdD20h62TORO2vgrjv2317AjTiib5KaK28HvscOzw0ujv/N4dLkPpJ5ow1fyAkjrDSY4wONxzhlJtIzp8oZ25PuxDj9V/L53Gqvcv6YcAnyYJR9vykziUV6cHImWI5gtvLW8L0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
