travis:
  secure:
    BINSTAR_TOKEN: Y+tsBcskcORSD8QqdVKGIoBpMLwtyStfRGakP8c27T6ura6RN91ag+mtsvxmU+1mLkmSS8XGdIE+uBudNGjVLemeTNnpRlGBHX4ohAhQ/kbHNSn1aIHnL8QZlAPNKLGIfYbS0lNdiESCMU8c740Psa9lx4y8rCn5avm126m1vS2pMTElcNnujcQfIglTJB6in3mk/DG0742jTrOhXyrYuGawAX7dmpi+RhcjbxO9kNCH30ajYvg3wLpHcbPGfjtOVDKh+xCgwpyGUZhaC/b3LUutybfHZ8TPYaEuHDfwLuTuIK1fftQDWaepJdrtfkOeG/rZKGcNLYCoKHph2DsylUhytYDYZcBswRRu/ih3zWodvfPrdciVCS1rEc5sY91JWi4RFW/lxVvbK1g39AAegZEOusQaWj59m8vC1sX+a/VrdVdHQAo35M+fAebwZSk45KfUrcP+8R+YUafChMq/TZzpRqDU34wdsuF27BLQ8FlTuBjk5qBgFO8Lg3h7YBXTv/2FV0eBcaH6kMO3EhNxo4Mny8epzsXaKh7KVeJWcHCisGLu9IGljRJwqFw+u0FPQIfG1Gs8LQ0ZqMFnwhaMHE/WjupnN1H2Jr2zr/p9tkGmRq+MF+0i3c+ra6swC4h4EdYxqqUzucKEQt0e5fAimKdgQX+3OXb/rBtgHHhnxgs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
