travis:
  secure:
    BINSTAR_TOKEN: FHGhyqhYx40+npEN2ZHP0CvgOpc05an5vuU/XC5b3OFZm9hlIx7Qm875TQT4MT/asZXkkt7OhtxLaOgpgqBl93bzoKr/8aj3CcqMhaSzxjqeka90pVn9VsCxY+yoPFXdXh3s5SwVd8IrMO/G78nxBOq4kZpNQUBxuzr+MxafWDQiS5d0syaBJIEVRxuQZsH/MQHEuQZJfqKk7yG1d5hCogrYSflOC1UxXjMavQo3/0FepTIBLc7LlMn+LJZLRaVWarp0Fkz27ctr+aPRczgR2Dybf+IFONYU8uNL3I3+SH3xoEhT+vjEMmeL8rcLdKPRIQ1rw1ihLquH4x1k33upDNRL46IysICXCnqleTn80lExsk7nDGtJy/YKzQPALCf08O38Lz6+mhdJy+Jy/MITD85kzAAbXyHZ18EWZzs13ckvfJTr3EaRk+5Nd5ToreN+YYtDSiHcB430SKT2d20ONF70bpDgvYiTbIQFvLkTT63ubie15/Sk7vvqX0OWDzyCf0w2la7NAWml+Ym0Crg7XJNyzbaQx3jz84PY0EBhJHOLy2KNv38EN78H8aQgegpF7Meszv8M8tiZ6lJGKxzHq+AYm7qBCJ7pyMYr6JT9taLKO94yAzFqTZ2We2LClWjUC9vcbM4irDsSmP+og8ia+M+y4eVR0jHqxwaHqqwDdPI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
